---
# defaults file for mariadb
mysql_user_home: /root
mysql_user_name: root
mysql_user_password: root

mysql_root_home: /root
mysql_root_username: root
mysql_root_password: root

mysql_install_packages: true
